bootcamp_app/ASPNETCoreMVCLojaVirtual/Código-Fonte - Passo a Passo/Seção 18/03_Fim/LojaVirtual/Models/EnderecoEntrega.cs
using LojaVirtual.Libraries.Lang;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace LojaVirtual.Models
{
    public class EnderecoEntrega
    {
        //PK
        public int Id { get; set; }

        [Required(ErrorMessageResourceType = typeof(Mensagem), ErrorMessageResourceName = "MSG_E001")]
        [MinLength(3, ErrorMessageResourceType = typeof(Mensagem), ErrorMessageResourceName = "MSG_E002")]
        public string Nome { get; set; }

        [Required(ErrorMessageResourceType = typeof(Mensagem), ErrorMessageResourceName = "MSG_E001")]
        [MinLength(10, ErrorMessageResourceType = typeof(Mensagem), ErrorMessageResourceName = "MSG_E002")]
        [MaxLength(10, ErrorMessageResourceType = typeof(Mensagem), ErrorMessageResourceName = "MSG_E003")]
        public string CEP { get; set; }

        [Required(ErrorMessageResourceType = typeof(Mensagem), ErrorMessageResourceName = "MSG_E001")]
        public string Estado { get; set; }

        [Required(ErrorMessageResourceType = typeof(Mensagem), ErrorMessageResourceName = "MSG_E001")]
        public string Cidade { get; set; }

        [Required(ErrorMessageResourceType = typeof(Mensagem), ErrorMessageResourceName = "MSG_E001")]
        public string Bairro { get; set; }

        [Display(Name = "Endereço")]
        [Required(ErrorMessageResourceType = typeof(Mensagem), ErrorMessageResourceName = "MSG_E001")]
        public string Endereco { get; set; }

        [Required(ErrorMessageResourceType = typeof(Mensagem), ErrorMessageResourceName = "MSG_E001")]
        public string Complemento { get; set; }

        [Display(Name = "Número")]
        public string Numero { get; set; }

        [ForeignKey("Cliente")]
        public int? ClienteId { get; set; }
                
        public virtual Cliente Cliente { get; set; }
    }
}

bootcamp_app/ASPNETCoreMVCLojaVirtual/Código-Fonte - Passo a Passo/Seção 18/03_Fim/LojaVirtual/Controllers/CarrinhoCompraController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LojaVirtual.Libraries.CarrinhoCompra;
using LojaVirtual.Models;
using LojaVirtual.Models.ProdutoAgregador;
using LojaVirtual.Repositories.Contracts;
using Microsoft.AspNetCore.Mvc;
using AutoMapper;
using LojaVirtual.Libraries.Lang;
using LojaVirtual.Models.Contants;
using LojaVirtual.Libraries.Gerenciador.Frete;
using LojaVirtual.Controllers.Base;
using LojaVirtual.Libraries.Login;
using LojaVirtual.Libraries.Filtro;
using Newtonsoft.Json;
using LojaVirtual.Libraries.Seguranca;

namespace LojaVirtual.Controllers
{
    public class CarrinhoCompraController : BaseController
    {
        public CarrinhoCompraController(
            LoginCliente loginCliente, 
            CookieCarrinhoCompra carrinhoCompra, 
            IEnderecoEntregaRepository enderecoEntregaRepository, 
            IProdutoRepository produtoRepository, 
            IMapper mapper, 
            WSCorreiosCalcularFrete wscorreios, 
            CalcularPacote calcularPacote, 
            CookieFrete cookieValorPrazoFrete) 
            : base(
                  loginCliente, 
                  carrinhoCompra, 
                  enderecoEntregaRepository, 
                  produtoRepository, 
                  mapper, 
                  wscorreios, 
                  calcularPacote, 
                  cookieValorPrazoFrete)
        { }
        
        public IActionResult Index()
        {
            List<ProdutoItem> produtoItemCompleto = CarregarProdutoDB();

            return View(produtoItemCompleto);
        }


        //Item ID = ID Produto
        public IActionResult AdicionarItem(int id)
        {
            Produto produto = _produtoRepository.ObterProduto(id);

            if(produto == null)
            {
                return View("NaoExisteItem");
            }
            else
            {
                var item = new ProdutoItem() { Id = id, QuantidadeProdutoCarrinho = 1 };
                _cookieCarrinhoCompra.Cadastrar(item);

                return RedirectToAction(nameof(Index));
            }
        }
        public IActionResult AlterarQuantidade(int id, int quantidade)
        {
            Produto produto = _produtoRepository.ObterProduto(id);
            if(quantidade < 1)
            {
                return BadRequest(new { mensagem = Mensagem.MSG_E007 });
            }else if (quantidade > produto.Quantidade)
            {
                return BadRequest(new { mensagem = Mensagem.MSG_E008 });
            }
            else
            {
                var item = new ProdutoItem() { Id = id, QuantidadeProdutoCarrinho = quantidade };
                _cookieCarrinhoCompra.Atualizar(item);
                return Ok(new { mensagem = Mensagem.MSG_S001 });
            }
        }
        public IActionResult RemoverItem(int id)
        {
            _cookieCarrinhoCompra.Remover(new ProdutoItem() { Id = id });
            return RedirectToAction(nameof(Index));
        }

        [ClienteAutorizacao]
        public IActionResult EnderecoEntrega()
        {
            Cliente cliente = _loginCliente.GetCliente();
            IList<EnderecoEntrega> enderecos = _enderecoEntregaRepository.ObterTodosEnderecoEntregaCliente(cliente.Id);

            ViewBag.Produtos = CarregarProdutoDB();
            ViewBag.Cliente = cliente;
            ViewBag.Enderecos = enderecos;

            return View();
        }


        public async Task<IActionResult> CalcularFrete(int cepDestino)
        {
            try {
                //Verifica se existe no Frete o calculo para o mesmo CEP e produtos.
                Frete frete = _cookieFrete.Consultar().Where(a => a.CEP == cepDestino && a.CodCarrinho == GerarHash(_cookieCarrinhoCompra.Consultar())).FirstOrDefault();
                if(frete != null)
                {
                    return Ok(frete);
                } else { 

                    List<ProdutoItem> produtos = CarregarProdutoDB();
                    List<Pacote> pacotes = _calcularPacote.CalcularPacotesDeProdutos(produtos);

                    ValorPrazoFrete valorPAC = await _wscorreios.CalcularFrete(cepDestino.ToString(), TipoFreteConstant.PAC, pacotes);
                    ValorPrazoFrete valorSEDEX = await _wscorreios.CalcularFrete(cepDestino.ToString(), TipoFreteConstant.SEDEX, pacotes);
                    ValorPrazoFrete valorSEDEX10 = await _wscorreios.CalcularFrete(cepDestino.ToString(), TipoFreteConstant.SEDEX10, pacotes);

                    List<ValorPrazoFrete> lista = new List<ValorPrazoFrete>();
                    if(valorPAC != null) lista.Add(valorPAC);
                    if(valorSEDEX != null) lista.Add(valorSEDEX);
                    if(valorSEDEX10 != null) lista.Add(valorSEDEX10);
                
                    frete = new Frete()
                    {
                        CEP = cepDestino,
                        CodCarrinho = GerarHash( _cookieCarrinhoCompra.Consultar() ),
                        ListaValores = lista
                    };
                
                    _cookieFrete.Cadastrar(frete);

                    return Ok(frete);
                }
            }
            catch (Exception e)
            {
                return BadRequest(e);
            }
        }
    }
}

bootcamp_app/ASPNETCoreMVCLojaVirtual/Código-Fonte - Passo a Passo/Seção 18/03_Fim/LojaVirtual/Controllers/PagamentoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using AutoMapper;
using LojaVirtual.Controllers.Base;
using LojaVirtual.Libraries.CarrinhoCompra;
using LojaVirtual.Libraries.Cookie;
using LojaVirtual.Libraries.Filtro;
using LojaVirtual.Libraries.Gerenciador.Frete;
using LojaVirtual.Libraries.Gerenciador.Pagamento.PagarMe;
using LojaVirtual.Libraries.Lang;
using LojaVirtual.Libraries.Login;
using LojaVirtual.Libraries.Texto;
using LojaVirtual.Models;
using LojaVirtual.Models.Contants;
using LojaVirtual.Models.ProdutoAgregador;
using LojaVirtual.Models.ViewModels.Pagamento;
using LojaVirtual.Repositories.Contracts;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using PagarMe;
using LojaVirtual.Libraries.AutoMapper;
using LojaVirtual.Libraries.Email;

namespace LojaVirtual.Controllers
{
    [ClienteAutorizacao]
    [ValidateCookiePagamentoController]
    public class PagamentoController : BaseController
    {
        private Cookie _cookie;
        private GerenciarPagarMe _gerenciarPagarMe;
        private IPedidoRepository _pedidoRepository;
        private IPedidoSituacaoRepository _pedidoSituacaRepository;
        private GerenciarEmail _gerenciarEmail;

        public PagamentoController(
            GerenciarEmail gerenciarEmail,
            IPedidoRepository pedidoRepository,
            IPedidoSituacaoRepository pedidoSituacaRepository,
            GerenciarPagarMe gerenciarPagarMe,
            LoginCliente loginCliente,
            Cookie cookie, 
            CookieCarrinhoCompra carrinhoCompra, 
            IEnderecoEntregaRepository enderecoEntregaRepository, 
            IProdutoRepository produtoRepository, 
            IMapper mapper, 
            WSCorreiosCalcularFrete wscorreios, 
            CalcularPacote calcularPacote, 
            CookieFrete cookieValorPrazoFrete) 
            : base(
                  loginCliente,
                  carrinhoCompra, 
                  enderecoEntregaRepository, 
                  produtoRepository, 
                  mapper, 
                  wscorreios, 
                  calcularPacote, 
                  cookieValorPrazoFrete)
        {
            _gerenciarEmail = gerenciarEmail;
            _pedidoRepository = pedidoRepository;
            _pedidoSituacaRepository = pedidoSituacaRepository;
            _cookie = cookie;
            _gerenciarPagarMe = gerenciarPagarMe;
        } 

        [HttpGet]
        public IActionResult Index()
        {
            List<ProdutoItem> produtoItemCompleto = CarregarProdutoDB();
            ValorPrazoFrete frete = ObterFrete();

            ViewBag.Frete = frete;
            ViewBag.Produtos = produtoItemCompleto;
            ViewBag.Parcelamentos = CalcularParcelamento(produtoItemCompleto);

            return View("Index");
        }

        [HttpPost]
        public IActionResult Index([FromForm]IndexViewModel indexViewModel)
        {
            if(ModelState.IsValid)
            {
                EnderecoEntrega enderecoEntrega = ObterEndereco();
                ValorPrazoFrete frete = ObterFrete();
                List<ProdutoItem> produtos = CarregarProdutoDB();
                Parcelamento parcela = BuscarParcelamento(produtos, indexViewModel.Parcelamento.Numero);

                try
                {
                    Transaction transaction = _gerenciarPagarMe.GerarPagCartaoCredito(indexViewModel.CartaoCredito, parcela, enderecoEntrega, frete, produtos);
                    Pedido pedido = ProcessarPedido(produtos, transaction);

                    return new RedirectToActionResult("Index", "Pedido", new { id = pedido.Id });
                }
                catch (PagarMeException e)
                {
                    TempData["MSG_E"] = MontarMensagensDeErro(e);

                    return Index();
                }
            }
            else
            {
                return Index();
            }
            
        }
        public IActionResult BoletoBancario()
        {
            EnderecoEntrega enderecoEntrega = ObterEndereco();
            ValorPrazoFrete frete = ObterFrete();
            List<ProdutoItem> produtos = CarregarProdutoDB();
            var valorTotal = ObterValorTotalCompra(produtos);

            try
            {
                Transaction transaction = _gerenciarPagarMe.GerarBoleto(valorTotal, produtos, enderecoEntrega, frete);
                
                Pedido pedido = ProcessarPedido(produtos, transaction);

                return new RedirectToActionResult("Index", "Pedido", new { id = pedido.Id });
            }
            catch (PagarMeException e)
            {
                TempData["MSG_E"] = MontarMensagensDeErro(e);
                return RedirectToAction(nameof(Index));
            }
        }

        private Pedido ProcessarPedido(List<ProdutoItem> produtos, Transaction transaction)
        {
            TransacaoPagarMe transacaoPagarMe;
            Pedido pedido;

            SalvarPedido(produtos, transaction, out transacaoPagarMe, out pedido);

            SalvarPedidoSituacao(produtos, transacaoPagarMe, pedido);

            DarBaixaNoEstoque(produtos);

            _cookieCarrinhoCompra.RemoverTodos();

            _gerenciarEmail.EnviarDadosDoPedido(_loginCliente.GetCliente(), pedido);

            return pedido;
        }

        private void DarBaixaNoEstoque(List<ProdutoItem> produtos)
        {
            foreach (var produto in produtos)
            {
                Produto produtoDB = _produtoRepository.ObterProduto(produto.Id);
                produtoDB.Quantidade -= produto.QuantidadeProdutoCarrinho;

                _produtoRepository.Atualizar(produtoDB);
            }
        }

        private void SalvarPedidoSituacao(List<ProdutoItem> produtos, TransacaoPagarMe transacaoPagarMe, Pedido pedido)
        {
            TransactionProduto tp = new TransactionProduto { Transaction = transacaoPagarMe, Produtos = produtos };
            PedidoSituacao pedidoSituacao = _mapper.Map<Pedido, PedidoSituacao>(pedido);
            pedidoSituacao = _mapper.Map<TransactionProduto, PedidoSituacao>(tp, pedidoSituacao);

            pedidoSituacao.Situacao = PedidoSituacaoConstant.AGUARDANDO_PAGAMENTO;

            _pedidoSituacaRepository.Cadastrar(pedidoSituacao);
        }

        private void SalvarPedido(List<ProdutoItem> produtos, Transaction transaction, out TransacaoPagarMe transacaoPagarMe, out Pedido pedido)
        {
            transacaoPagarMe = _mapper.Map<TransacaoPagarMe>(transaction);
            pedido = _mapper.Map<TransacaoPagarMe, Pedido>(transacaoPagarMe);
            pedido = _mapper.Map<List<ProdutoItem>, Pedido>(produtos, pedido);

            pedido.Situacao = PedidoSituacaoConstant.AGUARDANDO_PAGAMENTO;

            _pedidoRepository.Cadastrar(pedido);
        }

        private Parcelamento BuscarParcelamento(List<ProdutoItem> produtos, int numero)
        {
            return _gerenciarPagarMe.CalcularPagamentoParcelado(ObterValorTotalCompra(produtos)).Where(a => a.Numero == numero).First();
        }
        private EnderecoEntrega ObterEndereco()
        {
            EnderecoEntrega enderecoEntrega = null;
            var enderecoEntregaId = int.Parse(_cookie.Consultar("Carrinho.Endereco", false).Replace("-end", ""));

            if (enderecoEntregaId == 0)
            {
                Cliente cliente = _loginCliente.GetCliente();
                enderecoEntrega = _mapper.Map<EnderecoEntrega>(cliente);
            }
            else
            {
                var endereco = _enderecoEntregaRepository.ObterEnderecoEntrega(enderecoEntregaId);
            }

            return enderecoEntrega;
        }
        private ValorPrazoFrete ObterFrete()
        {
            var enderecoEntrega = ObterEndereco();
            int cep = int.Parse(Mascara.Remover(enderecoEntrega.CEP));
            var tipoFreteSelecionadoPeloUsuario = _cookie.Consultar("Carrinho.TipoFrete", false);
            var carrinhoHash = GerarHash(_cookieCarrinhoCompra.Consultar());
            
            Frete frete = _cookieFrete.Consultar().Where(a => a.CEP == cep && a.CodCarrinho == carrinhoHash).FirstOrDefault();

            if (frete != null)
            {
                return frete.ListaValores.Where(a => a.TipoFrete == tipoFreteSelecionadoPeloUsuario).FirstOrDefault();
            }
            return null;
        }
        private decimal ObterValorTotalCompra(List<ProdutoItem> produtos)
        {
            ValorPrazoFrete frete = ObterFrete();
            decimal total = Convert.ToDecimal( frete.Valor );

            foreach (var produto in produtos)
            {
                total += produto.Valor * produto.QuantidadeProdutoCarrinho;
            }

            return total;
        }
        private List<SelectListItem> CalcularParcelamento(List<ProdutoItem> produtos)
        {
            var total = ObterValorTotalCompra(produtos);
            var parcelamento = _gerenciarPagarMe.CalcularPagamentoParcelado(total);

            
            return parcelamento.Select(a => new SelectListItem(
                String.Format(
                    "{0}x {1} {2} - TOTAL: {3}",
                    a.Numero, a.ValorPorParcela.ToString("C"), (a.Juros) ? "c/ juros" : "s/ juros", a.Valor.ToString("C")
                ),
                a.Numero.ToString()
            )).ToList();
        }
        private string MontarMensagensDeErro(PagarMeException e)
        {
            StringBuilder sb = new StringBuilder();

            if (e.Error.Errors.Count() > 0)
            {
                sb.Append("Erro no pagamento: ");

bootcamp_app/ASPNETCoreMVCLojaVirtual/Código-Fonte - Passo a Passo/Seção 18/03_Fim/LojaVirtual/Views/CarrinhoCompra/EnderecoEntrega.cshtml

@{
    ViewData["Title"] = "EnderecoEntrega";

    var produtos = (List<ProdutoItem>)ViewBag.Produtos;
    decimal total = 0;

    foreach (ProdutoItem produto in produtos)
    {
        decimal resultado = produto.Valor * produto.QuantidadeProdutoCarrinho;
        total += resultado;
    }
}

<div class="container">
    <br />
    <br />
    <div class="row">
        <div class="col-md-12">
            @{ await Html.RenderPartialAsync("~/Views/Shared/_Mensagem.cshtml"); }

            <table class="table table-hover">
                <tbody>
                    <tr>
                        <th scope="row">
                            <input type="radio" name="endereco" value="0" id="0-end" />
                            <input type="hidden" name="cep" value="@ViewBag.Cliente.CEP" />
                        </th>
                        <td>
                            <label for="0-end">
                                <strong>Nome: </strong> Endereço do cliente.
                                <p>
                                    @ViewBag.Cliente.CEP | @ViewBag.Cliente.Estado, @ViewBag.Cliente.Cidade, @ViewBag.Cliente.Bairro, @ViewBag.Cliente.Endereco, @ViewBag.Cliente.Complemento, @ViewBag.Cliente.Numero
                                </p>
                            </label>
                        </td>
                    </tr>

                    @foreach (EnderecoEntrega endereco in ViewBag.Enderecos)
                    {
                        <tr>
                            <th scope="row">
                                <input type="radio" name="endereco" value="@endereco.Id" id="@endereco.Id-end" />
                                <input type="hidden" name="cep" value="@endereco.CEP" />
                            </th>
                            <td>
                                <label for="@endereco.Id-end">
                                    <strong>Nome: </strong> @endereco.Nome
                                    <p>
                                        @endereco.CEP | @endereco.Estado, @endereco.Cidade, @endereco.Bairro, @endereco.Endereco, @endereco.Complemento, @endereco.Numero
                                    </p>
                                </label>
                            </td>
                        </tr>
                    }


                </tbody>
            </table>



            <div class="text-center">
                <a asp-action="CadastroEnderecoEntrega" asp-controller="Home" asp-area="Cliente" asp-route-returnUrl="@Url.Action("EnderecoEntrega", "CarrinhoCompra", new { area = ""})" class="btn btn-outline-primary">Cadastrar novo endereço</a>
            </div>

            <br />
            <div class="card-group">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">-</h5>
                        <p class="card-text">-</p>
                    </div>
                    <div class="card-footer">
                        <small class="text-muted">
                            -
                        </small>
                    </div>
                </div>
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">-</h5>
                        <p class="card-text">-</p>
                    </div>
                    <div class="card-footer">
                        <small class="text-muted">
                            -
                        </small>
                    </div>
                </div>
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">-</h5>
                        <p class="card-text">-</p>
                    </div>
                    <div class="card-footer">
                        <small class="text-muted">
                            -
                        </small>
                    </div>
                </div>
            </div>
            <br />
            <div class="card-group">
                <div class="card">

                    <div class="card-body">
                        <h5 class="card-title">Produtos</h5>
                        <p class="card-text texto-produto">@total.ToString("C")</p>

                    </div>
                </div>
                <div class="card">

                    <div class="card-body">
                        <h5 class="card-title">Frete</h5>
                        <p class="card-text texto-frete">-</p>
                    </div>
                </div>
                <div class="card">

                    <div class="card-body">
                        <h5 class="card-title">Total</h5>
                        <p class="card-text texto-total">-</p>
                    </div>
                </div>
            </div>


            <br />
            <a asp-action="Index" asp-controller="Pagamento" class="btn btn-primary btn-continuar disabled">Continuar</a>
        </div>

    </div>
</div>


bootcamp_app/ASPNETCoreMVCLojaVirtual/Código-Fonte - Passo a Passo/Seção 18/03_Fim/LojaVirtual/Views/CarrinhoCompra/NaoExisteItem.cshtml

@{
    ViewData["Title"] = "NaoExisteItem";
}

<div class="container">
    <h1>Não encontramos o produto desejado</h1>
    <p>
        Opps! O produto desejado para o adicionar no carrinho não foi encontrado em nossos registros!
    </p>
</div>
